### PR TITLE
Remove custom status disclaimers and note.

### PR DESCRIPTION
**Pull request by jan-ivar**
***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 3, 2022, 9:08 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fjan-ivar%2Fmediacapture-viewport%2F05a97e00ed9bf4d3ad993ab3cbb5f805ac4a57e8%2Findex.html%3FisPreview%3Dtrue)

```
📡 HTTP Error 404: http://labs.w3.org/spec-generator/uploads/SC9h5e
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/mediacapture-viewport%2317.)._
</details>

### CODE REVIEW

**Comment by jan-ivar** [comment]
@dontcallmedom The PR Preview error looks unrelated to this PR to me, but I can't tell. Can the "sotd" not be empty? I noticed other specs we recently moved to FPWD don't have it at all. What's best practice here?

**Comment by jan-ivar** [comment]
Hmm, in contrast, mediacapture-main still says "This document is not complete. The API is based on preliminary work done in the WHATWG." (what WHATWG work is that I wonder?)

Should we perhaps not remove the part that says the API is not complete then? Should I file an issue on mediacapture-handle to add similar language?

**Comment by dontcallmedom** [comment]
I think it would be fair to remove the "not complete" bit from mediacapture-main.

(getUserMedia started in HTML LS, hence the ack)

I don't have strong feelings either way about keeping the bits about being complete or not.

**Comment by dontcallmedom** [comment]
the CI error is due to #16

**Review by eladalon1983 — APPROVED** [review]

**Review by youennf — APPROVED** [review]

**Pull request merged**
