### PR TITLE
Set [Restrictable] on the video track

### PR DESCRIPTION
**Pull request by eladalon1983**
This marks video tracks obtained using getViewportMedia() as eligible tracks for [Element Capture](https://screen-share.github.io/element-capture/).

***
<a href="https://pr-preview.s3.amazonaws.com/eladalon1983/mediacapture-viewport/pull/31.html" title="Last updated on Oct 9, 2024, 11:27 AM UTC (17ab171)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-viewport/31/976a130...eladalon1983:17ab171.html" title="Last updated on Oct 9, 2024, 11:27 AM UTC (17ab171)">Diff</a>

### CODE REVIEW

**Comment by youennf** [comment]
Should there be a PR on element capture as well?

**Comment by eladalon1983** [comment]
> Should there be a PR on element capture as well?

There was: https://github.com/screen-share/element-capture/pull/49

**Review by youennf — COMMENTED** [review]
Looks ok to me.
Overall, I feel like we should use https://w3c.github.io/mediacapture-main/#dfn-create-a-mediastreamtrack here, and pass the restrictable value to it.

**Comment by eladalon1983** [comment]
> Looks ok to me.

Great!

> Overall, I feel like we should use https://w3c.github.io/mediacapture-main/#dfn-create-a-mediastreamtrack here, and pass the restrictable value to it.

If you feel strongly, I am not opposed. But please consider that the current change is less intrusive, and could be rolled back more easily if need be, with less changes to other specs.

**Review by jan-ivar — APPROVED** [review]

**Pull request merged**
